# all packages used:
name: site
channels:
 - pytorch
 - huggingface
 - nvidia
 - defaults
dependencies:
  - python=3.12.2
  - datasets=2.14.3
  - jupyter=1.0.0
  - matplotlib=3.10.0
  - numpy=1.26.4
  - pandas=2.2.2
  - plotly=5.9.0
  - pytorch=2.3.1
  - pip=23.2.1
  - scikit-learn=1.3.0
  - seaborn=0.12.2
  - sentencepiece=0.2.0
  - tqdm=4.66.2
  - openpyxl=3.1.5
  - pip:
    - git+https://github.com/davidbau/baukit@main#egg=baukit
    - transformers==4.51.3
    - bitsandbytes
    - huggingface-hub==0.30.2
    - accelerate==0.26.0
    - fairscale
    - openai